language: python
python:
    - "3.6"
before_install:
  - pip install codecov
install:
    - pip install -r requirements.txt
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python tests/tests_clean_outliers_methods.py
  - python tests/tests_extract_features.py
  - coverage run tests/tests_clean_outliers_methods.py
  - coverage run tests/tests_extract_features.py
after_success:
  - codecov